server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 8092
  servlet:
    context-path: /hospital-api

#spring:
#  datasource:
#    driver-class-name: org.apache.phoenix.queryserver.client.Driver
#    url: jdbc:phoenix:172.16.6.0:2181
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      test-on-borrow: true
#      test-while-idle: true
#      max-active: 8
#      min-idle: 4
#      validation-query: SELECT 1
spring:
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:172.16.6.0:2181:/hbase
    username: none
    password: none
    connection-properties: phoenix.schema.isNamespaceMappingEnabled=true
    connectionProperties:  phoenix.schema.isNamespaceMappingEnabled=true
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    # 池中维护的最小空闲连接数
    minimum-idle: 10
    # 池中最大连接数，包括闲置和使用中的连接
    maximum-pool-size: 20
    # 此属性控制从池返回的连接的默认自动提交行为。默认为 true
    auto-commit: true
    # 允许最长空闲时间
    idle-timeout: 30000
    # 此属性表示连接池的用户定义名称，主要显示在日志记录和 JMX 管理控制台中，以标识池和池配置。 默认值：自动生成
    pool-name: custom-hikari
    #此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30 分钟
    max-lifetime: 1800000
    # 数据库连接超时时间,默认 30 秒，即 30000
    connection-timeout: 30000
    # 连接测试 sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
    connection-test-query: SELECT 1
  phoenixDataSource:
    url: jdbc:phoenix:172.16.6.0:2181:/hbase
    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
    username: ""
    password: ""
    connection-properties: phoenix.schema.isNamespaceMappingEnabled=true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 0
    host: 172.16.6.0
    port: 6379
    password: 888816280
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false


wechat:
  app-id: wx4cb8e9621950da45
  app-secret: 9d80f4125c50e1cf8bc6031c9319b2df
  pay:
    v3:
      patient-wx-api:
        app-id: wx4cb8e9621950da45
        app-v3-secret: 6c6085b7a939450d833d8bb3081d4628
        mch-id: 1526972031
        domain: http://172.16.6.0:9090/hospital-wx-api
        cert-path: apiclient_cert.p12

tencent:
  cloud:
    appId: 123123
    secretId: 123123
    secretKey: 123123
    face:
      groupName: hospital
      region: ap-beijing
  trtc:
    appId: 123123
    secretKey: 123123
    expire: 86400

minio:
  endpoint: http://172.16.6.0:9002
  access-key: root
  secret-key: 888816280

